FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/base:0-jammy

# Install additional packages as needed
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends \
#    ca-certificates \
#    curl \
#    jq \
#    git

# Set the default shell to bash rather than sh
ENV SHELL /bin/bash